use master
go

if not exists(select 1 from sys.databases where name = 'ThemeParks')
begin
    create database ThemeParks
end
go

use ThemeParks
go

if exists(select 1 from sys.tables where name = 'Parks')
begin
    drop table Parks
end
go

create table Parks
(
    Id int not null identity(1,1),
    Name nvarchar(50) not null,
    Description nvarchar(max) not null
)
go


insert into Parks (Name, Description) values ('Disneyland', '<p><b>Disneyland Park</b>, originally <b>Disneyland</b>, is the first of two <a href="/wiki/Theme_park" class="mw-redirect" title="Theme park">theme parks</a> built at the <a href="/wiki/Disneyland_Resort" title="Disneyland Resort">Disneyland Resort</a> in <a href="/wiki/Anaheim,_California" title="Anaheim, California">Anaheim, California</a>, opened on July 17, 1955. It is the only theme park designed and built under the direct supervision of <a href="/wiki/Walt_Disney" title="Walt Disney">Walt Disney</a>. It was originally the only attraction on the property; its official name was changed to Disneyland Park to distinguish it from the expanding complex in the 1990s.</p>
<p>Walt Disney came up with the concept of Disneyland after visiting various amusement parks with his daughters in the 1930s and 1940s. He initially envisioned building a tourist attraction adjacent to his <a href="/wiki/Walt_Disney_Studios_(Burbank)" title="Walt Disney Studios (Burbank)">studios</a> in <a href="/wiki/Burbank,_California" title="Burbank, California">Burbank</a> to entertain fans who wished to visit; however, he soon realized that the proposed site was too small. After hiring a consultant to help him determine an appropriate site for his project, Disney bought a 160-acre (65&nbsp;ha) site near Anaheim in 1953. Construction began in 1954 and the park was unveiled during a special televised press event on the <a href="/wiki/American_Broadcasting_Company" title="American Broadcasting Company">ABC</a> Television Network on July 17, 1955.</p>
<p>Since its opening, Disneyland has undergone a number of expansions and major renovations, including the addition of <a href="/wiki/New_Orleans_Square" title="New Orleans Square">New Orleans Square</a> in 1966, <a href="/wiki/Critter_Country" title="Critter Country">Bear Country</a> (now Critter Country) in 1972, <a href="/wiki/Mickey%27s_Toontown" title="Mickey''s Toontown">Mickey''s Toontown</a> in 1993, and the forthcoming <a href="/wiki/Star_Wars:_Galaxy%27s_Edge" title="Star Wars: Galaxy''s Edge"><i>Star Wars</i>: Galaxy''s Edge</a> in 2019.<sup id="cite_ref-Savvas_2-0" class="reference"><a href="#cite_note-Savvas-2">[2]</a></sup> Opened in 2001, <a href="/wiki/Disney_California_Adventure" title="Disney California Adventure">Disney California Adventure Park</a> was built on the site of Disneyland''s original parking lot.</p>
<p>Disneyland has a larger cumulative attendance than any other theme park in the world, with over 650 million guests since it opened. In 2013, the park hosted approximately 16.2 million guests, making it the third most visited park in the world that calendar year.<sup id="cite_ref-2013_attendance_3-0" class="reference"><a href="#cite_note-2013_attendance-3">[3]</a></sup><sup id="cite_ref-pimentel20150222_4-0" class="reference"><a href="#cite_note-pimentel20150222-4">[4]</a></sup> According to a March 2005 Disney report, 65,700 jobs are supported by the Disneyland Resort, including about 20,000 direct Disney employees and 3,800 third-party employees (<a href="/wiki/Independent_contractor" title="Independent contractor">independent contractors</a> or their employees).<sup id="cite_ref-5" class="reference"><a href="#cite_note-5">[5]</a></sup></p>')

insert into Parks (Name, Description) values ('Walt Disney World', '<p><span style="font-size: small;"><span id="coordinates"><a href="/wiki/Geographic_coordinate_system" title="Geographic coordinate system">Coordinates</a>: <span class="plainlinks nourlexpansion"><span style="white-space: nowrap;"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/WMA_button2b.png/17px-WMA_button2b.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/WMA_button2b.png/17px-WMA_button2b.png 1x, //upload.wikimedia.org/wikipedia/commons/thumb/5/55/WMA_button2b.png/34px-WMA_button2b.png 2x" class="wmamapbutton noprint" title="Show location on an interactive map" alt="" style="padding: 0px 3px 0px 0px; cursor: pointer;"><a class="external text" href="//tools.wmflabs.org/geohack/geohack.php?pagename=Walt_Disney_World&amp;params=28.385233_N_-81.563874_E_" style="white-space: nowrap;"><span class="geo-nondefault"><span class="geo-dms" title="Maps, aerial photos, and other data for this location"><span class="latitude">28°23''07?N</span> <span class="longitude">81°33''50?W</span></span></span><span class="geo-multi-punct">? / ?</span><span class="geo-default"><span class="geo-dec" title="Maps, aerial photos, and other data for this location">28.385233°N 81.563874°W</span><span style="display:none">? / <span class="geo">28.385233; -81.563874</span></span></span></a></span></span></span></span> The <b>Walt Disney World Resort</b> is an entertainment complex in <a href="/wiki/Bay_Lake,_Florida" title="Bay Lake, Florida">Bay Lake</a> and <a href="/wiki/Lake_Buena_Vista,_Florida" title="Lake Buena Vista, Florida">Lake Buena Vista</a>, <a href="/wiki/Florida" title="Florida">Florida</a>, near <a href="/wiki/Orlando,_Florida" title="Orlando, Florida">Orlando</a> and <a href="/wiki/Kissimmee,_Florida" title="Kissimmee, Florida">Kissimmee, Florida</a>. Opened on October 1, 1971, the resort is owned and operated by <a href="/wiki/Walt_Disney_Parks_and_Resorts" title="Walt Disney Parks and Resorts">Walt Disney Parks and Resorts</a>, a division of <a href="/wiki/The_Walt_Disney_Company" title="The Walt Disney Company">The Walt Disney Company</a>. It was initially operated by <a href="/wiki/Walt_Disney_World_Company" title="Walt Disney World Company">Walt Disney World Company</a>. The property covers 27,258 acres (43&nbsp;sq&nbsp;mi; 110&nbsp;km<sup>2</sup>), featuring four <a href="/wiki/Amusement_park" title="Amusement park">theme parks</a>, two <a href="/wiki/Water_park" title="Water park">water parks</a>, twenty-seven themed <a href="/wiki/Resort" title="Resort">resort hotels</a>, nine non–Disney hotels, several golf courses, a camping resort, and other entertainment venues, including <a href="/wiki/Disney_Springs" title="Disney Springs">Disney Springs</a>.</p>
<p>Designed to supplement <a href="/wiki/Disneyland" title="Disneyland">Disneyland</a> in <a href="/wiki/Anaheim,_California" title="Anaheim, California">Anaheim, California</a>, which had opened in 1955, the complex was developed by <a href="/wiki/Walt_Disney" title="Walt Disney">Walt Disney</a> in the 1960s. "The Florida Project", as it was known, was intended to present a distinct vision with its own diverse set of attractions. Walt Disney''s original plans also called for the inclusion of an "<a href="/wiki/EPCOT_(concept)" title="EPCOT (concept)">Experimental Prototype Community of Tomorrow</a>" (EPCOT), a <a href="/wiki/Planned_community" title="Planned community">planned community</a> intended to serve as a test bed for new city living innovations. After extensive lobbying, the <a href="/wiki/Government_of_Florida" title="Government of Florida">Government of Florida</a> created the <a href="/wiki/Reedy_Creek_Improvement_District" title="Reedy Creek Improvement District">Reedy Creek Improvement District</a>, a <a href="/wiki/Special-purpose_district" class="mw-redirect" title="Special-purpose district">special government district</a> that essentially gave The Walt Disney Company the standard powers and autonomy of an <a href="/wiki/Municipal_corporation" title="Municipal corporation">incorporated city</a>. Walt Disney died on December 15, 1966, before construction began. Without Disney spearheading the construction, the company created a resort similar to Disneyland, abandoning experimental concepts for a planned community. <a href="/wiki/Magic_Kingdom" title="Magic Kingdom">Magic Kingdom</a> was the first theme park to open in the complex, in 1971, followed by <a href="/wiki/Epcot" title="Epcot">Epcot</a> in 1982, <a href="/wiki/Disney%27s_Hollywood_Studios" title="Disney''s Hollywood Studios">Disney''s Hollywood Studios</a> in 1989, and the most recent, <a href="/wiki/Disney%27s_Animal_Kingdom" title="Disney''s Animal Kingdom">Disney''s Animal Kingdom</a> in 1998.</p>
<p>Today, Walt Disney World is the most visited vacation resort in the world, with an average annual attendance of over 52 million.<sup id="cite_ref-2" class="reference"><a href="#cite_note-2">[2]</a></sup> The resort is the flagship destination of Disney''s worldwide corporate enterprise, and has become a <a href="/wiki/Popular_culture" title="Popular culture">popular staple</a> in <a href="/wiki/Culture_of_the_United_States" title="Culture of the United States">American culture</a>.</p>')

insert into Parks (Name, Description) values ('Universal Studios Hollywood', '<p><b>Universal Studios Hollywood</b> is a <a href="/wiki/Film_studio" title="Film studio">film studio</a> and <a href="/wiki/Amusement_park" title="Amusement park">theme park</a> in the <a href="/wiki/San_Fernando_Valley" title="San Fernando Valley">San Fernando Valley</a> area of <a href="/wiki/Los_Angeles_County,_California" title="Los Angeles County, California">Los Angeles County, California</a>. About 70% of the studio lies within the unincorporated <a href="/wiki/County_island" title="County island">county island</a> known as <a href="/wiki/Universal_City,_California" title="Universal City, California">Universal City</a> while the rest lies within the city limits of <a href="/wiki/Los_Angeles,_California" class="mw-redirect" title="Los Angeles, California">Los Angeles, California</a>. It is one of the oldest and most famous Hollywood film studios still in use. Its official marketing headline is "The Entertainment Capital of LA".<sup id="cite_ref-AboutUs_1-1" class="reference"><a href="#cite_note-AboutUs-1">[1]</a></sup> It was initially created to offer tours of the real Universal Studios sets and is the first of many full-fledged <a href="/wiki/Universal_Parks_%26_Resorts" title="Universal Parks &amp; Resorts">Universal Studios Theme Parks</a> located across the world.</p>
<p>Outside the theme park, a new, all-digital facility near the <a href="/wiki/Universal_Studios" class="mw-redirect" title="Universal Studios">Universal Studios</a> backlot was built in an effort to merge all of NBCUniversal''s West Coast operations into one area. As a result, the current home for <a href="/wiki/KNBC" title="KNBC">KNBC</a>, <a href="/wiki/KVEA" title="KVEA">KVEA</a> and <a href="/wiki/NBC_News" title="NBC News">NBC News</a> with <a href="/wiki/Telemundo" title="Telemundo">Telemundo</a> Los Angeles Bureaus with new digital facility is on the Universal lot formerly occupied by <a href="/wiki/Technicolor_SA" title="Technicolor SA">Technicolor SA</a>. Universal City includes hotels Universal <a href="/wiki/Hilton_Hotels" class="mw-redirect" title="Hilton Hotels">Hilton</a> &amp; Towers, the <a href="/wiki/Sheraton_Hotels_and_Resorts" title="Sheraton Hotels and Resorts">Sheraton</a> Universal Hotel, and <a href="/wiki/Universal_CityWalk" title="Universal CityWalk">Universal CityWalk</a>, which offers a collection of shops, restaurants, an 18-screen Universal Cinema and a seven-story IMAX theater. In 2016, the park hosted 8,086,000 guests, ranking it 15th in the world and 9th among North American parks.<sup id="cite_ref-2013_attendance_3-0" class="reference"><a href="#cite_note-2013_attendance-3">[3]</a></sup></p>')

insert into Parks (Name, Description) values ('Six Flags', '<p><b>Six Flags</b>, officially <b>Six Flags Entertainment Corporation</b>, is an amusement park corporation based in the United States, with properties in the US, Canada, and Mexico. It is the largest amusement park company in the world, based on the number of properties owned, and is <a href="/wiki/List_of_amusement_park_attendance_figures" class="mw-redirect" title="List of amusement park attendance figures">ranked sixth</a> in terms of attendance.<sup id="cite_ref-tea2016_2-0" class="reference"><a href="#cite_note-tea2016-2">[2]</a></sup> The company maintains twenty properties throughout North America including theme parks, thrill parks, <a href="/wiki/Water_park" title="Water park">water parks</a>, and family entertainment centers. In 2016, Six Flags properties hosted over 30.1&nbsp;million guests.<sup id="cite_ref-tea2016_2-1" class="reference"><a href="#cite_note-tea2016-2">[2]</a></sup></p>
<p>Six Flags was founded in Texas and derived its name from its first property, <a href="/wiki/Six_Flags_Over_Texas" title="Six Flags Over Texas">Six Flags Over Texas</a>. The company maintains a corporate office in <a href="/wiki/Midtown_Manhattan" title="Midtown Manhattan">Midtown Manhattan</a> and its headquarters are in <a href="/wiki/Grand_Prairie,_Texas" title="Grand Prairie, Texas">Grand Prairie, Texas</a>. On June 13, 2009, the corporation filed for Chapter 11 <a href="/wiki/Bankruptcy_protection" class="mw-redirect" title="Bankruptcy protection">bankruptcy protection</a>, which it successfully exited after restructuring on May 3, 2010.<sup id="cite_ref-3" class="reference"><a href="#cite_note-3">[3]</a></sup><sup id="cite_ref-PressRelease0613_4-0" class="reference"><a href="#cite_note-PressRelease0613-4">[4]</a></sup><sup id="cite_ref-ExitCh11_5-0" class="reference"><a href="#cite_note-ExitCh11-5">[5]</a></sup></p>')
